[package]
name = "bytes-format"
version = "0.1.0"
keywords = ["serde"]
categories = ["encoding"]
edition = "2018"
publish = false

[dependencies]
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
serde_bytes = "0.11.5"
